// オブジェクトの情報
export const classInfo = {
    '1-1':{
        "class":"1年1組",
        "program":"1-1が縁日、やるってよ。",
        "category":"縁日",
        "comment":"『縁日、やるってよ。』",
        "location":"3_1",
        "photo": "",
        "iconFile":"./icon/1-1.png",
    },
    '1-2':{
        "class":"1年2組",
        "program":"レトロゲーム",
        "category":"ゲーム",
        "comment":"『どんなひとでもたのしめます！！』",
        "location":"2_3",
        "photo": "",
        "iconFile":"./icon/1-2.png",
    },
    '1-3':{
        "class":"1年3組",
        "program":"Journey to Time～歪んだ先の終着点～",
        "category":"脱出ゲーム",
        "comment":"『Journey to Time～歪んだ先の終着点～』",
        "location":"3_2",
        "photo": "",
        "iconFile":"./icon/1-3.png",
    },
    '1-4':{
        "class":"1年4組",
        "program":"平成GALクラブ",
        "category":"クラブ",
        "comment":"『やっほ～！ゥチらちょーかわいいGALでぇ～す♡我等友情永久不滅♡』",
        "location":"2_2",
        "photo": "",
        "iconFile":"./icon/1-4.png",
    },
    '2-1':{
        "class":"2年1組",
        "program":"パーラーやっしー",
        "category":"屋台",
        "comment":"『お腹も心も満たす　焼きそば』",
        "location":"1_1",
        "photo": "",
        "iconFile":"./icon/2-1.png",
    },
    '2-2':{
        "class":"2年2組",
        "program":"甘味処　茶屋",
        "category":"茶屋",
        "comment":"『伝統文化は金になる　さぁどうぞ』",
        "location":"3_6",
        "photo": "",
        "iconFile":"./icon/2-2.png",
    },
    '2-3':{
        "class":"2年3組",
        "program":"★お化け屋敷★",
        "category":"お化け屋敷",
        "comment":"『廃校で起きた未解決殺人事件！その真相を暴き、君は現実に戻れるか？』",
        "location":"2_4",
        "photo": "",
        "iconFile":"./icon/2-3.png",
    },
    '2-4':{
        "class":"2年4組",
        "program":"縁日",
        "category":"縁日",
        "comment":"『江戸時代にタイムトラベルしたあなた。斬って撃って投げて、めいっぱい楽しんでください！目指せ、ランキング１位！！』",
        "location":"1_4",
        "photo": "",
        "iconFile":"./icon/2-4.png",
    },
    '3-ms':{
        "class":"3年機械",
        "program":"REMOVE BEFORE FLIGHT",
        "category":"フライトシミュレータ",
        "comment":"REMOVE BEFORE FLIGHT",
        "location":"3_7",
        "photo": "",
        "iconFile":"./icon/3-ms.png",
    },
    '3-br':{
        "class":"3年生物",
        "program":"串屋はまちゃん",
        "category":"屋台",
        "comment":"『はっ、はっ、はまちゃん！</br>　鶏肉や野菜を、鉄板で一本一本丁寧に焼き上げ、はまい串に。</br>　自然のおいしさ、そのままに』",
        "location":"1_1",
        "photo": "",
        "iconFile":"./icon/3-br.jpg",
    },
    '3-mi':{
        "class":"3年メディア",
        "program":"自作ボードゲーム",
        "category":"ゲーム",
        "comment":"自分たちでボードゲーム作りました.^-^)/",
        "location":"2_6",
        "photo": "",
        "iconFile":"./icon/3-mi.png",
    },
    '3-ic':{
        "class":"3年情報",
        "program":"縁日バー",
        "category":"縁日バー",
        "comment":"楽しませます",
        "location":"2_1",
        "photo": "",
        "iconFile":"./icon/3-ic.png",
    },
    '4-ms':{
        "class":"4年機械",
        "program":"マッスル屋台",
        "category":"屋台",
        "comment":"『今日だけは筋肉のために』",
        "location":"1_1",
        "photo": "",
        "iconFile":"./icon/4-ms.png",
    },
    '4-br':{
        "class":"4年生物",
        "program":"コンカフェ",
        "category":"カフェ",
        "comment":"『楽しんでいってください』",
        "location":"1_1",
        "photo": "",
        "iconFile":"./icon/4-br.png",
    },
    '4-mi':{
        "class":"4年メディア",
        "program":"謎解きアクションゲーム",
        "category":"脱出ゲーム",
        "comment":"『アクションをクリアして謎を解け』",
        "location":"1_2",
        "photo": "",
        "iconFile":"./icon/4-mi.png",
    },
    '4-ic':{
        "class":"4年情報",
        "program":"カジノ",
        "category":"カジノ",
        "comment":"去年大人気だったルーレットは引き続き、新しく江戸にタイムスリップしたかのような気分になれる花札で遊べます。場内チップを介して楽しく賭けてみてください。",
        "location":"3_4",
        "photo": "",
        "iconFile":"./icon/4-ic.png",
    },
    '5-ms':{
        "class":"5年機械",
        "program":"お化け屋敷",
        "category":"お化け屋敷",
        "comment":"",
        "location":"3_3",
        "photo": "",
        "iconFile":"./icon/5-ms.png",
    },
    '5-br':{
        "class":"5年生物",
        "program":"フォトスポット",
        "category":"フォトスポット",
        "comment":"『最後の高専祭頑張りましたのでぜひご覧ください』",
        "location":"2_5",
        "photo": "",
        "iconFile":"./icon/5-br.jpeg",
    },
    '5-mi':{
        "class":"5年メディア",
        "program":"カジノ",
        "category":"カジノ",
        "comment":"『今 か ら 皆 さ ん に は ゲ ー ム を し て い た だ き ま す 。(デスゲーム風ボイス)』",
        "location":"1_3",
        "photo": "",
        "iconFile":"./icon/5-mi.png",
    },
    '5-ic':{
        "class":"5年情報",
        "program":"平成友だちん家喫茶",
        "category":"喫茶",
        "comment":"『友だちん家に行っていた時を思い出せる喫茶店です』",
        "location":"3_5",
        "photo": "",
        "iconFile":"./icon/5-ic.png",
    },
};