// オブジェクトの情報
export const Info = {
    //１階
    'F1':{
        "description":"説明さ",
        "Position":[0,5,0],
        "cameraPosition":[-40,35,70],
    },
    '1_1':{
        "description":"説明さ",
        "Position":[-20,5,5],
        "cameraPosition":[-20,5,30],
    },
    '1_2':{
        "description":"説明さ",
        "Position":[-11.5,5,5],
        "cameraPosition":[-11.5,5,30],
    },
    '1_3':{
        "description":"説明さ",
        "Position":[15,5,5],
        "cameraPosition":[15,5,30],
    },
    '1_4':{
        "description":"説明さ",
        "Position":[23,5,5],
        "cameraPosition":[23,5,30],
    },
    'Stair1':{
        "description":"説明さ",
        "Position":[0,0,0],
        "cameraPosition":[0,0,0],
    },
    //２階
    'F2':{
        "description":"説明さ",
        "Position":[0,25,0],
        "cameraPosition":[-40,55,70],
    },
    '2_1':{
        "description":"説明さ",
        "Position":[-20,28,5],
        "cameraPosition":[-20,28,30],
    },
    '2_2':{
        "description":"説明さ",
        "Position":[-11.5,28,5],
        "cameraPosition":[-11.5,28,30],
    },
    '2_3':{
        "description":"説明さ",
        "Position":[15,28,5],
        "cameraPosition":[15,28,30],
    },
    '2_4':{
        "description":"説明さ",
        "Position":[23,28,5],
        "cameraPosition":[23,28,30],
    },
    '2_5':{
        "description":"説明さ",
        "Position":[5,28,-6],
        "cameraPosition":[5,28,-32.1],
    },
    'zinja':{
        "description":"説明さ",
        "Position":[25,27.6,-5],
        "cameraPosition":[33.8,27.6,-5],
    },
    'Stair2':{
        "description":"説明さ",
        "Position":[0,0,0],
        "cameraPosition":[0,0,0],
    },
    //３階
    'F3':{
        "description":"説明さ",
        "Position":[0,50,0],
        "cameraPosition":[-40,80,70],
    },
    '3_1':{
        "description":"説明さ",
        "Position":[-20,53,5],
        "cameraPosition":[-20,53,30],
    },
    '3_2':{
        "description":"説明さ",
        "Position":[-11.5,53,5],
        "cameraPosition":[-11.5,53,30],
    },
    '3_3':{
        "description":"説明さ",
        "Position":[15,53,5],
        "cameraPosition":[15,53,30],
    },
    '3_4':{
        "description":"説明さ",
        "Position":[23,53,5],
        "cameraPosition":[23,53,30],
    },
    '3_5':{
        "description":"説明さ",
        "Position":[23,53.53,1.78],
        "cameraPosition":[-48,53.53,1.78],
    },
    '3_6':{
        "description":"説明さ",
        "Position":[23,53.53,-3],
        "cameraPosition":[47,53.53,-3],
    },
    'Stair3':{
        "description":"説明さ",
        "Position":[0,0,0],
        "cameraPosition":[0,0,0],
    },

    'invisible':{
        "description":"説明さ",
        "Position":[0,0,0],
        "cameraPosition":[0,0,0],
    },
    'invisible2':{
        "description":"説明さ",
        "Position":[0,0,0],
        "cameraPosition":[0,0,0],
    },
    'invisible3':{
        "description":"説明さ",
        "Position":[0,0,0],
        "cameraPosition":[0,0,0],
    },
    'invisible4':{
        "description":"説明さ",
        "Position":[0,0,0],
        "cameraPosition":[0,0,0],
    },

};