// オブジェクトの情報
export const Info = {
    //１階
    'F1':{
        "description":"説明さ",
        "Position":[0,5,0],
        "cameraPosition":[-40,35,70],
    },
    '1_1':{
        "description":"説明さ",
        "Position":[0,0,0],
        "cameraPosition":[0,0,0],
    },
    '1_2':{
        "description":"説明さ",
        "Position":[0,0,0],
        "cameraPosition":[0,0,0],
    },
    '1_3':{
        "description":"説明さ",
        "Position":[0,0,0],
        "cameraPosition":[0,0,0],
    },
    '1_4':{
        "description":"説明さ",
        "Position":[0,0,0],
        "cameraPosition":[0,0,0],
    },
    'Stair1':{
        "description":"説明さ",
        "Position":[0,0,0],
        "cameraPosition":[0,0,0],
    },
    //２階
    'F2':{
        "description":"説明さ",
        "Position":[0,25,0],
        "cameraPosition":[-40,55,70],
    },
    '2_1':{
        "description":"説明さ",
        "Position":[-20,28,5],
        "cameraPosition":[-20,28,30],
    },
    '2_2':{
        "description":"説明さ",
        "Position":[-11.5,28,5],
        "cameraPosition":[-11.5,28,30],
    },
    '2_3':{
        "description":"説明さ",
        "Position":[15,28,5],
        "cameraPosition":[15,28,30],
    },
    '2_4':{
        "description":"説明さ",
        "Position":[23,28,5],
        "cameraPosition":[23,28,30],
    },
    '2_5':{
        "description":"説明さ",
        "Position":[0,0,0],
        "cameraPosition":[0,0,0],
    },
    'zinja':{
        "description":"説明さ",
        "Position":[0,0,0],
        "cameraPosition":[0,0,0],
    },
    'Stair2':{
        "description":"説明さ",
        "Position":[0,0,0],
        "cameraPosition":[0,0,0],
    },
    //３階
    'F3':{
        "description":"説明さ",
        "Position":[0,50,0],
        "cameraPosition":[-40,80,70],
    },
    '3_1':{
        "description":"説明さ",
        "Position":[0,0,0],
        "cameraPosition":[0,0,0],
    },
    '3_2':{
        "description":"説明さ",
        "Position":[0,0,0],
        "cameraPosition":[0,0,0],
    },
    '3_3':{
        "description":"説明さ",
        "Position":[0,0,0],
        "cameraPosition":[0,0,0],
    },
    '3_4':{
        "description":"説明さ",
        "Position":[0,0,0],
        "cameraPosition":[0,0,0],
    },
    '3_5':{
        "description":"説明さ",
        "Position":[0,0,0],
        "cameraPosition":[0,0,0],
    },
    '3_6':{
        "description":"説明さ",
        "Position":[0,0,0],
        "cameraPosition":[0,0,0],
    },
    'Stair3':{
        "description":"説明さ",
        "Position":[0,0,0],
        "cameraPosition":[0,0,0],
    },

    'invisible':{
        "description":"説明さ",
        "Position":[0,0,0],
        "cameraPosition":[0,0,0],
    },
    'invisible2':{
        "description":"説明さ",
        "Position":[0,0,0],
        "cameraPosition":[0,0,0],
    },
    'invisible3':{
        "description":"説明さ",
        "Position":[0,0,0],
        "cameraPosition":[0,0,0],
    },
    'invisible4':{
        "description":"説明さ",
        "Position":[0,0,0],
        "cameraPosition":[0,0,0],
    },

};