// オブジェクトの情報
export const classInfo = {
    '1-1':{
        "className":"1年1組",
        "program":"1-1が縁日、やるってよ。",
        "category":"game",
        "comment":"『縁日、やるってよ。』",
        "location":"3_1",
        "photo": "./photo/1-1.jpg",
        "iconFile":"./icon/1-1.png",
    },
    '1-2':{
        "className":"1年2組",
        "program":"レトロゲーム",
        "category":"game",
        "comment":"『どんなひとでもたのしめます！！』",
        "location":"2_3",
        "photo": "./photo/1-2.jpg",
        "iconFile":"./icon/1-2.png",
    },
    '1-3':{
        "className":"1年3組",
        "program":"Journey to Time～歪んだ先の終着点～",
        "category":"walk",
        "comment":"『Journey to Time～歪んだ先の終着点～』",
        "location":"3_2",
        "photo": "./photo/1-3.jpg",
        "iconFile":"./icon/1-3.png",
    },
    '1-4':{
        "className":"1年4組",
        "program":"平成GALクラブ",
        "category":"amusement",
        "comment":"『やっほ～！ゥチらちょーかわいいGALでぇ～す♡我等友情永久不滅♡』",
        "location":"2_2",
        "photo": "./photo/1-4.jpg",
        "iconFile":"./icon/1-4.jpg",
    },
    '2-1':{
        "className":"有志屋台",
        "program":"五年情報",
        "category":"stall",
        "comment":"焼きそば、うどん、トルティーヤ、じゃがバター、フランクフルト、ドリンク",
        "location":"yata2",
        "photo": "./photo/entama.jpg",
        "iconFile":"./photo/entama.png",
    },
    '2-2':{
        "className":"2年2組",
        "program":"甘味処　茶屋",
        "category":"eat",
        "comment":"『伝統文化は金になる　さぁどうぞ』",
        "location":"3_6",
        "photo": "./photo/2-2.jpg",
        "iconFile":"./icon/2-2.png",
    },
    '2-3':{
        "className":"2年3組",
        "program":"★お化け屋敷★",
        "category":"walk",
        "comment":"『廃校で起きた未解決殺人事件！その真相を暴き、君は現実に戻れるか？』",
        "location":"2_4",
        "photo": "./photo/2-3.jpg",
        "iconFile":"./icon/2-3.png",
    },
    '2-4':{
        "className":"2年4組",
        "program":"縁日",
        "category":"game",
        "comment":"『江戸時代にタイムトラベルしたあなた。斬って撃って投げて、めいっぱい楽しんでください！目指せ、ランキング１位！！』",
        "location":"1_4",
        "photo": "./photo/2-4.jpg",
        "iconFile":"./icon/2-4.png",
    },
    '3-ms':{
        "className":"3年機械",
        "program":"REMOVE BEFORE FLIGHT",
        "category":"other",
        "comment":"REMOVE BEFORE FLIGHT",
        "location":"3_7",
        "photo": "./photo/3-ms.jpg",
        "iconFile":"./icon/3-ms.png",
    },
    '3-br':{
        "className":"有志屋台",
        "program":"WSB国際交流委員会",
        "category":"stall",
        "comment":"ロティ、チャナイ、グリーンカレー、タイティー",
        "location":"yata3",
        "photo": "./photo/entama.jpg",
        "iconFile":"./photo/entama.jpg",
    },
    '3-mi':{
        "className":"3年メディア",
        "program":"自作ボードゲーム",
        "category":"game",
        "comment":"自分たちでボードゲーム作りました.^-^)/",
        "location":"2_6",
        "photo": "./photo/3-mi.jpg",
        "iconFile":"./icon/3-mi.png",
    },
    '3-ic':{
        "className":"3年情報",
        "program":"縁日バー",
        "category":"game",
        "comment":"楽しませます",
        "location":"2_1",
        "photo": "./photo/3-ic.jpg",
        "iconFile":"./icon/3-ic.png",
    },
    '4-ms':{
        "className":"有志屋台",
        "program":"TEAMMID(UMAI・D)",
        "category":"stall",
        "comment":"たこ焼き・ドリンク",
        "location":"yata1",
        "photo": "./photo/entama.jpg",
        "iconFile":"./photo/entama.png",
    },
    '4-br':{
        "className":"4年生物",
        "program":"コンカフェ",
        "category":"eat",
        "comment":"『楽しんでいってください』",
        "location":"1_1",
        "photo": "./photo/4-br.jpg",
        "iconFile":"./icon/4-br.png",
    },
    '4-mi':{
        "className":"4年メディア",
        "program":"謎解きアクションゲーム",
        "category":"walk",
        "comment":"『アクションをクリアして謎を解け』",
        "location":"1_2",
        "photo": "./photo/4-mi.jpeg",
        "iconFile":"./icon/4-mi.png",
    },
    '4-ic':{
        "className":"4年情報",
        "program":"カジノ",
        "category":"game",
        "comment":"去年大人気だったルーレットは引き続き、新しく江戸にタイムスリップしたかのような気分になれる花札で遊べます。場内チップを介して楽しく賭けてみてください。",
        "location":"3_4",
        "photo": "./photo/4-ic.jpeg",
        "iconFile":"./icon/4-ic.png",
    },
    '5-ms':{
        "className":"5年機械",
        "program":"お化け屋敷",
        "category":"walk",
        "comment":"",
        "location":"3_3",
        "photo": "./photo/entama.jpg",
        "iconFile":"./icon/5-ms.png",
    },
    '5-br':{
        "className":"5年生物",
        "program":"フォトスポット",
        "category":"art",
        "comment":"『最後の高専祭頑張りましたのでぜひご覧ください』",
        "location":"2_5",
        "photo": "./photo/entama.jpg",
        "iconFile":"./icon/5-br.jpeg",
    },
    '5-mi':{
        "className":"5年メディア",
        "program":"カジノ",
        "category":"game",
        "comment":"『今 か ら 皆 さ ん に は ゲ ー ム を し て い た だ き ま す 。(デスゲーム風ボイス)』",
        "location":"1_3",
        "photo": "./photo/5-mi.jpg",
        "iconFile":"./icon/5-mi.png",
    },
    '5-ic':{
        "className":"5年情報",
        "program":"平成友だちん家喫茶",
        "category":"eat",
        "comment":"『友だちん家に行っていた時を思い出せる喫茶店です』",
        "location":"3_5",
        "photo": "./photo/5-ic.jpeg",
        "iconFile":"./icon/5-ic.png",
    },
    'zinja':{
        "className":"zinja",
        "program":"高専神社",
        "category":"神社",
        "comment":"",
        "location":"zinja",
        "photo": "",
        "iconFile":"",
    },
};